service: socie

custom:
  stage: ${opt:stage,"default"}
  db_name: gbf_twitter_token_${self:custom.stage}

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  role: ${env:LAMBDA_IAM}
  tracing:
    apiGateway: true
    lambda: true

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  request_token:
    handler: bin/oath/request
    environment: 
      CONSUMER_KEY: ${env:CK}
      CONSUMER_SECRET: ${env:CS}
      CALLBACK_URL: ${env:CALLBACK_URL}
    events:
      - http:
          path: /oath/request
          method: get
  access_token:
    handler: bin/oath/access
    environment: 
      CONSUMER_KEY: ${env:CK}
      CONSUMER_SECRET: ${env:CS}
      DB_NAME: ${self:custom.db_name}
    events:
      - http:
          path: /oath/callback
          method: get
  delete_batch:
    handler: bin/batch/delete
    environment: 
      CONSUMER_KEY: ${env:CK}
      CONSUMER_SECRET: ${env:CS}
      DB_NAME: ${self:custom.db_name}
    events:
      - schedule: cron(0 * * * ? *)

# DynamoDBを作る
resources:
  Resources:
    pso2commonDB:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.db_name}
        AttributeDefinitions:
        - AttributeName: UserID
          AttributeType: S
        KeySchema:
        - AttributeName: UserID
          KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1